import * as fs from 'fs';
import * as path from 'path';
import { AuditResult } from './auditor.js';

export function fixEnvExample(result: AuditResult, targetFile?: string): string {
  const examplePath = targetFile || path.join(result.rootDir, '.env.example');

  // Combine all keys from both .env files and codebase usages
  const combinedKeys = new Set<string>([
    ...Array.from(result.allEnvKeys),
    ...Array.from(result.allCodeKeys),
  ]);

  const sortedKeys = Array.from(combinedKeys).sort();

  const lines: string[] = [
    '# Auto-generated by keydrift',
    `# Updated: ${new Date().toISOString()}`,
    '',
  ];

  sortedKeys.forEach((key) => {
    // Look up existing value or default placeholder
    let sampleValue = 'your_' + key.toLowerCase() + '_here';

    for (const ef of result.envFiles) {
      const entry = ef.entries.get(key);
      if (entry && entry.hasValue) {
        // Obfuscate secret values in .env.example
        if (isSecretKey(key)) {
          sampleValue = 'your_' + key.toLowerCase() + '_here';
        } else {
          sampleValue = entry.value;
        }
        break;
      }
    }

    lines.push(`${key}=${sampleValue}`);
  });

  const content = lines.join('\n') + '\n';
  const dir = path.dirname(examplePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(examplePath, content, 'utf-8');
  return examplePath;
}

function isSecretKey(key: string): boolean {
  const lk = key.toLowerCase();
  return (
    lk.includes('secret') ||
    lk.includes('key') ||
    lk.includes('password') ||
    lk.includes('token') ||
    lk.includes('auth') ||
    lk.includes('private')
  );
}
