import * as fs from 'fs';
import * as path from 'path';
import { AuditResult } from './auditor.js';

export function generateTypescriptDefs(result: AuditResult, targetPath?: string): string {
  const outPath = targetPath || path.join(result.rootDir, 'env.d.ts');

  const combinedKeys = new Set<string>([
    ...Array.from(result.allEnvKeys),
    ...Array.from(result.allCodeKeys),
  ]);

  const sortedKeys = Array.from(combinedKeys).sort();

  const lines: string[] = [
    '// Auto-generated by keydrift',
    'declare namespace NodeJS {',
    '  interface ProcessEnv {',
  ];

  sortedKeys.forEach((key) => {
    lines.push(`    ${key}?: string;`);
  });

  lines.push('  }');
  lines.push('}');
  lines.push('');

  const content = lines.join('\n');
  const dir = path.dirname(outPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(outPath, content, 'utf-8');
  return outPath;
}

export function generateGoStruct(result: AuditResult, targetPath?: string): string {
  const outPath = targetPath || path.join(result.rootDir, 'env_config.go');

  const combinedKeys = new Set<string>([
    ...Array.from(result.allEnvKeys),
    ...Array.from(result.allCodeKeys),
  ]);

  const sortedKeys = Array.from(combinedKeys).sort();

  const lines: string[] = [
    'package config',
    '',
    '// Config holds environment variables parsed at runtime.',
    'type Config struct {',
  ];

  sortedKeys.forEach((key) => {
    const fieldName = toPascalCase(key);
    lines.push(`\t${fieldName} string \`env:"${key}"\``);
  });

  lines.push('}');
  lines.push('');

  const content = lines.join('\n');
  fs.writeFileSync(outPath, content, 'utf-8');
  return outPath;
}

function toPascalCase(s: string): string {
  return s
    .toLowerCase()
    .split('_')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
}
